#!/usr/bin/env python3
"""Cuts a continuous voice take into lines and prints the offset table as TS.

Splitting is done on silence: ffmpeg reports every quiet stretch, and anything
longer than MERGE_GAP is treated as the gap between two lines rather than a
breath inside one. Each line is then tagged by length, which is the only signal
available without understanding the words — a hurt grunt is short, a contact
call is a beat or two, and anything long is chatter. Retag by hand in the
generated file if a line lands in the wrong bucket.
"""
import re
import subprocess
import sys

# Quiet enough to be a gap, measured against the normalised take.
NOISE_FLOOR = '-30dB'
# Shortest stretch ffmpeg should bother reporting.
MIN_SILENCE = 0.12
# Gaps shorter than this are breaths inside a line, not the end of one.
MERGE_GAP = 0.25
# Kept either side of a cut so consonants aren't clipped off.
PAD = 0.05
# Anything shorter than this is a lip smack or a page turn, not a line.
MIN_LINE = 0.35
# A bark this long stops reading as a bark, so anything over it is split again
# at its own quietest interior pause even though that pause was short enough to
# look like a breath.
MAX_LINE = 4.0

TAGS = [(1.15, 'short'), (2.6, 'mid')]


def silences(path):
    out = subprocess.run(
        ['ffmpeg', '-hide_banner', '-nostats', '-i', path,
         '-af', f'silencedetect=noise={NOISE_FLOOR}:d={MIN_SILENCE}', '-f', 'null', '-'],
        capture_output=True, text=True, check=True).stderr
    spans, start = [], None
    for kind, value in re.findall(r'silence_(start|end): (-?[\d.]+)', out):
        if kind == 'start':
            start = float(value)
        elif start is not None:
            spans.append((start, float(value)))
            start = None
    return spans


def duration(path):
    return float(subprocess.run(
        ['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
         '-of', 'csv=p=0', path], capture_output=True, text=True, check=True).stdout)


def split(a, b, gaps):
    """Halves an over-long line at its widest interior pause, recursively."""
    if b - a <= MAX_LINE:
        return [(a, b)]
    inside = [g for g in gaps if a + MIN_LINE < g[0] and g[1] < b - MIN_LINE]
    if not inside:
        return [(a, b)]
    at = max(inside, key=lambda g: g[1] - g[0])
    return split(a, at[0], gaps) + split(at[1], b, gaps)


def lines(path):
    total = duration(path)
    gaps = silences(path)
    bounds, at = [], 0.0
    for a, b in (g for g in gaps if g[1] - g[0] >= MERGE_GAP):
        bounds.append((at, a))
        at = b
    bounds.append((at, total))

    out = []
    for a, b in bounds:
        for a2, b2 in split(a, b, gaps):
            a2, b2 = max(0.0, a2 - PAD), min(total, b2 + PAD)
            if b2 - a2 >= MIN_LINE:
                out.append((round(a2, 3), round(b2 - a2, 3)))
    return out


def tag(length):
    for limit, name in TAGS:
        if length < limit:
            return name
    return 'long'


def main(paths):
    print('/**')
    print(' * Enemy voice lines — GENERATED by tools/slice-voice.py, do not hand-edit')
    print(' * offsets. Each entry is a slice of the take in public/sfx of the same')
    print(' * name: `at` seconds in, `len` seconds long.')
    print(' *')
    print(" * `tag` is what the line gets used for and is the one field worth editing:")
    print(' * the slicer guesses it from length alone, so move a line between buckets')
    print(' * by hand once you have heard it. See audio/Voices.ts for what each bucket')
    print(' * is spoken over.')
    print(' */')
    print()
    print("export type VoiceTag = 'short' | 'mid' | 'long';")
    print()
    print('export interface VoiceLine {')
    print('  /** Seconds into the take. */')
    print('  readonly at: number;')
    print('  /** Seconds of speech. */')
    print('  readonly len: number;')
    print('  readonly tag: VoiceTag;')
    print('}')
    print()
    print('/** One take per speaker; a bot is assigned one for its whole life. */')
    print('export interface VoiceTake {')
    print('  /** File in public/sfx, without the extension. */')
    print('  readonly file: string;')
    print('  readonly lines: readonly VoiceLine[];')
    print('}')
    print()
    print('export const VOICE_TAKES: readonly VoiceTake[] = [')
    for path in paths:
        name = path.rsplit('/', 1)[-1].rsplit('.', 1)[0]
        print(f"  {{")
        print(f"    file: '{name}',")
        print('    lines: [')
        for i, (at, length) in enumerate(lines(path)):
            print(f"      {{ at: {at:.3f}, len: {length:.3f}, tag: '{tag(length)}' }},  // {i}")
        print('    ],')
        print('  },')
    print('];')


if __name__ == '__main__':
    main(sys.argv[1:])
