/**
 * Enemy voice lines — GENERATED by tools/slice-voice.py, do not hand-edit
 * offsets. Each entry is a slice of the take in public/sfx of the same
 * name: `at` seconds in, `len` seconds long.
 *
 * `tag` is what the line gets used for and is the one field worth editing:
 * the slicer guesses it from length alone, so move a line between buckets
 * by hand once you have heard it. See audio/Voices.ts for what each bucket
 * is spoken over.
 */

export type VoiceTag = 'short' | 'mid' | 'long';

export interface VoiceLine {
  /** Seconds into the take. */
  readonly at: number;
  /** Seconds of speech. */
  readonly len: number;
  readonly tag: VoiceTag;
}

/** One take per speaker; a bot is assigned one for its whole life. */
export interface VoiceTake {
  /** File in public/sfx, without the extension. */
  readonly file: string;
  readonly lines: readonly VoiceLine[];
}

export const VOICE_TAKES: readonly VoiceTake[] = [
  {
    file: 'voice-a',
    lines: [
      { at: 0.000, len: 1.208, tag: 'mid' },  // 0
      { at: 1.391, len: 1.865, tag: 'mid' },  // 1
      { at: 3.918, len: 1.528, tag: 'mid' },  // 2
      { at: 5.616, len: 1.869, tag: 'mid' },  // 3
      { at: 8.097, len: 2.224, tag: 'mid' },  // 4
      { at: 10.642, len: 1.886, tag: 'mid' },  // 5
      { at: 13.081, len: 3.857, tag: 'long' },  // 6
      { at: 17.421, len: 1.383, tag: 'mid' },  // 7
      { at: 19.038, len: 1.158, tag: 'mid' },  // 8
      { at: 20.463, len: 1.601, tag: 'mid' },  // 9
      { at: 22.330, len: 2.967, tag: 'long' },  // 10
      { at: 25.337, len: 1.965, tag: 'mid' },  // 11
      { at: 27.454, len: 2.129, tag: 'mid' },  // 12
    ],
  },
  {
    file: 'voice-b',
    lines: [
      { at: 0.391, len: 1.716, tag: 'mid' },  // 0
      { at: 2.647, len: 3.374, tag: 'long' },  // 1
      { at: 6.318, len: 1.102, tag: 'short' },  // 2
      { at: 7.720, len: 1.426, tag: 'mid' },  // 3
      { at: 9.309, len: 1.060, tag: 'short' },  // 4
      { at: 11.049, len: 1.067, tag: 'short' },  // 5
      { at: 12.422, len: 3.498, tag: 'long' },  // 6
      { at: 15.996, len: 1.081, tag: 'short' },  // 7
      { at: 18.040, len: 2.629, tag: 'long' },  // 8
      { at: 21.257, len: 0.577, tag: 'short' },  // 9
      { at: 22.006, len: 1.180, tag: 'mid' },  // 10
      { at: 23.536, len: 1.893, tag: 'mid' },  // 11
      { at: 26.171, len: 1.865, tag: 'mid' },  // 12
      { at: 28.360, len: 1.078, tag: 'short' },  // 13
      { at: 29.940, len: 2.511, tag: 'mid' },  // 14
      { at: 33.530, len: 2.530, tag: 'mid' },  // 15
      { at: 36.656, len: 1.883, tag: 'mid' },  // 16
      { at: 39.167, len: 1.582, tag: 'mid' },  // 17
      { at: 41.551, len: 0.674, tag: 'short' },  // 18
      { at: 42.395, len: 1.164, tag: 'mid' },  // 19
      { at: 43.746, len: 1.734, tag: 'mid' },  // 20
    ],
  },
];
